spring:
    profiles:
        active: dev
mybatis:
    mapper-locations:
     - classpath:com/report/mapper/*.xml                       # mapper映射文件
    configuration:
        call-setters-on-nulls: true
        log-impl: org.apache.ibatis.logging.stdout.StdOutImpl



